---

- hosts: webserver
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution_version == "Ubuntu"
  - name: install apache2 package
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution_version == "Ubuntu"
  - name: add php sup for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution_version == "Ubuntu"

  - name: update repo index
    dnf:
      update_cache: yes
    when: ansible_distribution_version == "CentOS"
  - name: install apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution_version == "CentOS"
  - name: add php sup for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution_version == "CentOS"
